### PR TITLE
Update Matsim_Tutorial.rst

### PR DESCRIPTION
**Pull request by arnaudcan**
I just corrected some typos.
Check that I'm right with the LDEN_GEOM replacing LDAY_GEOM in the attenuation matrix name.
By the way that would be less confusing to call it more simply "ATTENUATION_MATRIX", no ?

### CODE REVIEW

**Comment by pierromond** [comment]
@Nitnelav can you check before we merge ?
> Check that I'm right with the LDEN_GEOM replacing LDAY_GEOM in the attenuation matrix name.
> By the way that would be less confusing to call it more simply "ATTENUATION_MATRIX", no ?

**Comment by nicolas-f** [comment]
>  By the way that would be less confusing to call it more simply "ATTENUATION_MATRIX", no ?

Sorry it should be:

Do not compute LDEN_GEOM table : true

Can you fix that ?

WPS NoiseLevelFromSource goal is to compute LDEN values. So attenuation matrix is like a workaround. A specific WPS script for attenuation matrix should be used instead.

**Review by Nitnelav — CHANGES_REQUESTED** [review]
Yeah the LDEN_GEOM is not used since we only use the Day in the calculations. So we should keep the LDAY_GEOM.

**Comment by Nitnelav** [comment]
> 
> 
> > By the way that would be less confusing to call it more simply "ATTENUATION_MATRIX", no ?
> 
> Sorry it should be:
> 
> Do not compute LDEN_GEOM table : true
> 
> Can you fix that ?
> 
> WPS NoiseLevelFromSource goal is to compute LDEN values. So attenuation matrix is like a workaround. A specific WPS script for attenuation matrix should be used instead.

true that

**Comment by Nitnelav** [comment]
we can merge and i'll apply the fixes in another PR

**Review by Nitnelav — APPROVED** [review]

**Pull request closed without merging**
