### PR TITLE
Fix building constraint in delaunay triangulation

### PR DESCRIPTION
**Pull request by nicolas-f**
- Fix building constraint in delaunay triangulation
- Allow triangulation without roads table
- javadoc

### CODE REVIEW

**Comment by nicolas-f** [comment]
Is it ok if there is triangles into the buildings in the new official release ? @pierromond @gpetit

**Comment by pierromond** [comment]
Could it be an option ?

**Comment by nicolas-f** [comment]
Option added in WPS

**Comment by nicolas-f** [comment]
Ready for review

**Pull request merged**
