### PR TITLE
Asc driver support of double type

### PR DESCRIPTION
**Pull request by nicolas-f**
import asc driver update from h2gis 2.0

### CODE REVIEW

**Comment by pierromond** [comment]
Lucky luke !

**Comment by ebocher** [comment]
Why importing the code and not use the H2GIS one ?

**Comment by nicolas-f** [comment]
@ebocher we are using h2gis 1.5

**Comment by ebocher** [comment]
You can  backport to 1.5. 
This has been already done for other function for NoiseModelling. There is build for that :  http://jenkins.orbisgis.org/job/H2GIS-1.5.X/
It's better than duplicating the code and this is also the foss philosophy ;-)

**Comment by pierromond** [comment]
> You can backport to 1.5.
I don't know what it means. Should we merge ? or wait ?

**Pull request merged**
