### PR TITLE
Fix index out of bound.

### PR DESCRIPTION
**Pull request by SPalominos**
Fix silly bug (issue #463)

### CODE REVIEW

**Comment by nicolas-f** [comment]
you have an issue with your algorithm.
When you remove an element the indices in the "element to remove" are no longer valid (because of shifting of elements)

**Comment by nicolas-f** [comment]
The most easy to read/understand algorithm is to build a new list will all elements to keep

**Comment by SPalominos** [comment]
Yes, you are right, I've pushed a wrong code,

**Comment by nicolas-f** [comment]
removeAll function is a very costly function as it will iterate NxN between the two lists. Are you sure you want to keep it like this ?

**Pull request closed without merging**
