### PR TITLE
Better matsim, better osm_pbf

### PR DESCRIPTION
**Pull request by Nitnelav**
- Improve the outputs of matsim agent exposure noise levels.
- Fix https://github.com/Ifsttar/NoiseModelling/issues/334

### CODE REVIEW

**Comment by nicolas-f** [comment]
SRID is set to be 2154. Is it ok or I it would be better to read the actual srid ?

**Comment by Nitnelav** [comment]
Good point. Fixed

**Comment by nicolas-f** [comment]
You could use receiversTable or dataTable. Using the method SFSUtilities.getSRID

**Comment by Nitnelav** [comment]
It would work because the geom data comes from a matsim file, without SRID information

**Comment by nicolas-f** [comment]
The SRID should be set when importing the data to the localdatabase

**Comment by Nitnelav** [comment]
importing the data to the localdatabase is what the script does.
The activities locations are red from the matsim files. The other tables are only used to get sound level values.
I agree that the other tables contain an information about activity locations, but it made sense to code it in a way that this information is taken from the matsim file instead (ie. iterate over activities per agent as a starting point)

**Review by pierromond — APPROVED** [review]

**Pull request merged**
